<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6d3a920e-c6e3-4695-9b74-76acfeccabc5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FanHubPlus.Application\FanHubPlus.Application.csproj" />
    <ProjectReference Include="..\FanHubPlus.Infrastructure\FanHubPlus.Infrastructure.csproj" />
  </ItemGroup>

</Project>
