-- ============================================================
-- Fan Hub Plus — Seed Data
-- ============================================================
-- STATUS: Placeholder. Will be written after 01_schema.sql.
--
-- Planned contents:
--   1. The 8 fandom categories:
--      Anime, Gaming, Movies, TV Shows, K-Pop, Comics, Manga, Cosplay
--   2. Demo accounts (passwords also documented in docs/credentials.md):
--      * admin@fanhubplus.test      (Admin role)
--      * user@fanhubplus.test       (Registered role)
--      * — visitors need no account
--   3. Sample content per category (articles, videos, audio, images)
--   4. Sample character profiles, merchandise items, upcoming releases,
--      and local fan events for the calendar/map feature
--
-- NOTE: Passwords must be stored ONLY as bcrypt/argon2 hashes in `users`.
-- ============================================================

-- Seed INSERTs will be added here during the build phase.
