-- ============================================================
-- Reference data, the rows every other file depends on.
-- ============================================================
-- LOAD ORDER MATTERS:
--   1. 01_schema.sql        (all 19 tables)
--   2. 04_*_seed.sql        (the five catalogue imports)
--   3. 05_reference_data.sql (this file, last)
--
--   This file runs LAST because the 04_* files insert categories 1-5 with a
--   plain INSERT. Loading this file first would insert those same five and the
--   04 files would then fail on a duplicate key. Running last, the upserts
--   below fill in the missing fandoms and add the roles table.
--
-- WHY THIS FILE IS SEPARATE
--   The 04_*_seed.sql files only insert categories and genres as a side
--   effect of importing titles. That leaves the `roles` table empty, so the
--   first account anyone registers would fail on a foreign key. This file
--   seeds the two things the schema needs before anything else can work.
--
-- This file is safe to run more than once, it uses upserts throughout, and
-- unlike the 04_* files it inserts no rows that a child table depends on
-- within the same transaction.
--
-- Charset: utf8mb4, matching the schema.

-- ---------- Roles ----------
-- The three roles from the SRS. `registered` is what a new sign-up is given;
-- `admin` is only ever assigned by an existing admin. `visitor` is not a row
-- the app assigns, it just means "not signed in", but it is listed so the
-- tier is visible in the table.

INSERT INTO roles (role_id, name, description) VALUES
  (1, 'visitor',     'Browses public content without an account'),
  (2, 'registered',  'Signed in: bookmarks, ratings, submissions, feedback'),
  (3, 'admin',       'Full control panel: content, users, moderation, stats')
ON DUPLICATE KEY UPDATE description = VALUES(description);

-- ---------- Categories ----------
-- The 8 fandoms in the SRS. The catalogue import inserts 5 of these
-- (movies, anime, gaming, comics, k-pop) because only those have title
-- lists; the other 3 exist so the site's navigation and filters match what
-- the frontend renders, and so a submission can be filed against them.

INSERT INTO categories (category_id, slug, name, description, accent_hex) VALUES
  (1, 'movies',     'Movies',     'Film from every era and genre',                 '#7c3aed'),
  (2, 'anime',      'Anime',      'Animated worlds, shonen battles and slice-of-life', '#ec4899'),
  (3, 'gaming',     'Gaming',     'Games, studios and the players behind them',   '#06b6d4'),
  (4, 'comics',     'Comics',     'Graphic novels, runs and collected editions',   '#f59e0b'),
  (5, 'k-pop',      'K-Pop',      'Groups, soloists and the industry around them', '#8b5cf6'),
  (6, 'tv-shows',   'TV Shows',   'Series from sitcoms to prestige drama',         '#14b8a6'),
  (7, 'manga',      'Manga',      'Japanese comics and their adaptations',        '#ef4444'),
  (8, 'cosplay',    'Cosplay',    'Costume craft, conventions and styling',       '#a855f7')
ON DUPLICATE KEY UPDATE
  name        = VALUES(name),
  description = VALUES(description),
  accent_hex  = VALUES(accent_hex);

-- ---------- Demo accounts ----------
-- Passwords are Argon2id hashes produced by the API's own
-- IPasswordHasher<User> (Microsoft.AspNetCore.Identity), so
-- AuthService can verify them without any extra configuration.
--
-- They are generated by:
--   dotnet run --project src/FanHubPlus.Api -- --hash-password <password>
-- which prints a hash for a fresh random salt. See backend/README.md.
--
-- The plaintext values are the demo passwords documented in
-- docs/credentials.md. They are deliberately obvious and must be changed
-- before any real deployment.
--
-- Each hash is salted per user, so they differ even though both passwords are
-- short. Regenerate with:
--   dotnet run --project src/FanHubPlus.Api -- --hash-password admin  --user "Ada Lovelace"
--   dotnet run --project src/FanHubPlus.Api -- --hash-password user123 --user "Grace Hopper"

-- Ada Lovelace (user_id 1) is the ONLY administrator. She is the single
-- original admin account: she is what the control panel is reached through, and
-- no other account is granted the admin role by any seed. Everyone else who
-- signs up is 'registered' by AuthService.RegisterAsync, and promotion to admin
-- is a deliberate act inside the panel by an existing admin.
INSERT INTO users (user_id, name, email, password_hash, is_verified, created_at, updated_at) VALUES
  (1, 'Ada Lovelace', 'admin@fanhubplus.com',
   'AQAAAAIAAYagAAAAEAvquVz5BICql3YYmHa1+hyiTD4UXYhiFu4VfhtOVZ65D4aqx2GNKxQN+6vIBSSScA==',
   1, NOW(), NOW()),
  (2, 'Grace Hopper', 'user@fanhubplus.test',
   'AQAAAAIAAYagAAAAEH1MSvGSlZsMdxwso1jsNovHjxXpTvOWSYEPE7jvW9Zu4xhUzO9ihnd5BHamRLryvg==',
   1, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name          = VALUES(name),
  -- email is included so re-running this file actually renames the account.
  -- Without it a database seeded under the previous address kept the old one
  -- and the documented credentials silently stopped working.
  email         = VALUES(email),
  password_hash = VALUES(password_hash),
  is_verified   = VALUES(is_verified);

-- 3 = admin, 2 = registered
--
-- Only user 1 is an admin. Every other account. Grace included, is
-- 'registered', which is also the only role RegisterAsync ever assigns. The
-- ON DUPLICATE KEY UPDATE below is what makes this file re-runnable as a
-- demotion: a database where somebody was promoted to admin in the panel goes
-- back to one admin when this is run again.
INSERT INTO user_roles (user_id, role_id) VALUES
  (1, 3),
  (2, 2)
ON DUPLICATE KEY UPDATE role_id = VALUES(role_id);
