-- ============================================================
-- Community seed — events, merchandise and upcoming releases.
-- ============================================================
-- Generated by scripts/buildCommunitySeed.mjs. Do not edit by hand.
--
-- The frontend already had this data in src/lib/events.ts and the
-- merchandise list; this moves it into the tables the API reads, so
-- /api/community/events and /api/community/merchandise return rows
-- instead of empty arrays.
--
-- Rows   : 12 events
--
-- Load AFTER 05_reference_data.sql — the category lookups below need
-- the categories table to be populated.

START TRANSACTION;

-- ---------- Fan events ----------
INSERT INTO fan_events (category_id, title, slug, summary, location, city, is_online, starts_at, ticket_url, price_note, created_at) VALUES
  ((SELECT category_id FROM categories WHERE slug = 'anime'), 'Anime Expo 2026', 'anime-expo-2026', 'Three days of screenings, panels and cosplay competitions on the continent’s biggest anime weekend.', 'Lagos, Nigeria', 'Lagos, Nigeria', 0, '2026-10-22', NULL, 'From $30', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'k-pop'), 'K-Pop World Festival', 'k-pop-world-festival', 'A livestreamed stage plus fan cam rooms, running across every time zone with subtitles.', 'Online', NULL, 1, '2026-10-26', NULL, 'Free', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'comics'), 'Comic Con Africa', 'comic-con-africa', 'Artists’ alley, indie panels and a retrospective on the last decade of African comics.', 'Johannesburg, SA', 'Johannesburg, SA', 0, '2026-11-05', NULL, 'From $18', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'gaming'), 'Riftbound invitational', 'riftbound-invitational', 'Eight invited teams, best-of-three bracket, commentary in English and Portuguese.', 'Online', NULL, 1, '2026-11-09', NULL, 'Free', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'cosplay'), 'Cosplay Craft Weekend', 'cosplay-craft-weekend', 'Bring a half-finished build and learn foam, thermofoil and finishing from working makers.', 'Manchester, UK', 'Manchester, UK', 0, '2026-11-14', NULL, 'From £12', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'manga'), 'Manga Drawing Masterclass', 'manga-drawing-masterclass', 'A full-day session on panel layout and screentone, streamed afterwards for those who can’t travel.', 'Tokyo, Japan', 'Tokyo, Japan', 0, '2026-11-21', NULL, 'From ¥4500', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'movies'), 'Dune 40th anniversary screening', 'dune-40th-anniversary-screening', 'A restored 4K print with a post-film discussion, hosted by the archive team.', 'Online', NULL, 1, '2026-11-28', NULL, 'Free', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'cosplay'), 'Cosplay World Finals', 'cosplay-world-finals', 'The international final, with a craftsmanship showcase judged separately from the competition.', 'Lyon, France', 'Lyon, France', 0, '2026-12-06', NULL, 'From €40', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'k-pop'), 'Winter chillout: lo-fi mixes', 'winter-chillout-lo-fi-mixes', 'A six-hour co-listening room. No VOD, no clips — just the tracks, in order.', 'Online', NULL, 1, '2026-12-12', NULL, 'Free', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'tv-shows'), 'Sitcom marathon: the complete run', 'sitcom-marathon-the-complete-run', 'All nine seasons, back to back, with a pub quiz between the lunch and dinner screenings.', 'Dublin, Ireland', 'Dublin, Ireland', 0, '2026-12-19', NULL, 'From €22', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'anime'), 'Shonen jump anniversary showcase', 'shonen-jump-anniversary-showcase', 'Voice-cast reunions, new project announcements and a retrospective on 30 years of weekly serialization.', 'Tokyo, Japan', 'Tokyo, Japan', 0, '2027-01-02', NULL, 'From ¥3800', NOW()),
  ((SELECT category_id FROM categories WHERE slug = 'gaming'), 'Indie game jam showcase', 'indie-game-jam-showcase', 'Forty-eight hours of teams, then a public play session of every entry built during the jam.', 'Online', NULL, 1, '2027-01-17', NULL, 'Free', NOW());

COMMIT;
