-- Generated by scripts/buildSuppliedArtSeed.mjs - do not edit by hand.
-- Source: the image files present in public/images/, not the original zips.
-- Rows: 45 merchandise_items, 14 character_profiles
--
-- Every image_path below points at a file this script just listed, so none of
-- them can be a dead link. Regenerate after adding or removing artwork.
--
-- Idempotent: INSERT.. SELECT.. WHERE NOT EXISTS throughout, so re-running
-- is a no-op rather than a duplicate-key error. Nothing is deleted.
--
-- Load AFTER 05_reference_data.sql - the category lookups need categories.

START TRANSACTION;

-- ---------- merchandise_items ----------
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Item 01', 'anime-item-01', '/images/merchandise/anime/anime-item-01.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-item-01');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Item 02', 'anime-item-02', '/images/merchandise/anime/anime-item-02.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-item-02');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Item 03', 'anime-item-03', '/images/merchandise/anime/anime-item-03.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-item-03');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Item 04', 'anime-item-04', '/images/merchandise/anime/anime-item-04.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-item-04');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Keychains', 'anime-keychains', '/images/merchandise/anime/anime-keychains.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-keychains');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Keychains I D Actually Like To Buy', 'anime-keychains-i-d-actually-like-to-buy', '/images/merchandise/anime/anime-keychains-i-d-actually-like-to-buy.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-keychains-i-d-actually-like-to-buy');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anime Plushie Said', 'anime-plushie-said', '/images/merchandise/anime/anime-plushie-said.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anime-plushie-said');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Anya Merch', 'anya-merch', '/images/merchandise/anime/anya-merch.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'anya-merch');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Best Anime Figures Collectibles Every Fan Should Own', 'best-anime-figures-collectibles-every-fan-should-own', '/images/merchandise/anime/best-anime-figures-collectibles-every-fan-should-own.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'best-anime-figures-collectibles-every-fan-should-own');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Custom Anime Water Bottle Collection Premium Drinkware Design For Bran', 'custom-anime-water-bottle-collection-premium-drinkware-design-for-bran', '/images/merchandise/anime/custom-anime-water-bottle-collection-premium-drinkware-design-for-bran.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'custom-anime-water-bottle-collection-premium-drinkware-design-for-bran');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Eu Qro', 'eu-qro', '/images/merchandise/anime/eu-qro.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'eu-qro');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Our Jujutsu Kaisen Lookup Figures Are Now Finally Available Pn Our Web', 'our-jujutsu-kaisen-lookup-figures-are-now-finally-available-pn-our-web', '/images/merchandise/anime/our-jujutsu-kaisen-lookup-figures-are-now-finally-available-pn-our-web.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'our-jujutsu-kaisen-lookup-figures-are-now-finally-available-pn-our-web');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Riyadh', 'riyadh', '/images/merchandise/anime/riyadh.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'riyadh');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Sodameow Anime Demon Backpack Nezuko Slayer Bag Kimetsu No Yaiba Backp', 'sodameow-anime-demon-backpack-nezuko-slayer-bag-kimetsu-no-yaiba-backp', '/images/merchandise/anime/sodameow-anime-demon-backpack-nezuko-slayer-bag-kimetsu-no-yaiba-backp.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'sodameow-anime-demon-backpack-nezuko-slayer-bag-kimetsu-no-yaiba-backp');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Tasse D Mon Slayer', 'tasse-d-mon-slayer', '/images/merchandise/anime/tasse-d-mon-slayer.jpg', 1
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'tasse-d-mon-slayer');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Attack On Titan Anime Men S T Shirt Summer Short Sleeved Cartoon Men W', 'attack-on-titan-anime-men-s-t-shirt-summer-short-sleeved-cartoon-men-w', '/images/merchandise/cosplay/attack-on-titan-anime-men-s-t-shirt-summer-short-sleeved-cartoon-men-w.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'attack-on-titan-anime-men-s-t-shirt-summer-short-sleeved-cartoon-men-w');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Cosplay Item 01', 'cosplay-item-01', '/images/merchandise/cosplay/cosplay-item-01.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'cosplay-item-01');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Cosplay Item 02', 'cosplay-item-02', '/images/merchandise/cosplay/cosplay-item-02.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'cosplay-item-02');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Cosplay Item 03', 'cosplay-item-03', '/images/merchandise/cosplay/cosplay-item-03.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'cosplay-item-03');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Cosplay Item 04', 'cosplay-item-04', '/images/merchandise/cosplay/cosplay-item-04.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'cosplay-item-04');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Monkey D Luffy Tokoh Fiktif One Piece', 'monkey-d-luffy-tokoh-fiktif-one-piece', '/images/merchandise/cosplay/monkey-d-luffy-tokoh-fiktif-one-piece.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'monkey-d-luffy-tokoh-fiktif-one-piece');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Narutos New Anime 500ml Stainless Steel Water Bottle Thermos Adult Lar', 'narutos-new-anime-500ml-stainless-steel-water-bottle-thermos-adult-lar', '/images/merchandise/cosplay/narutos-new-anime-500ml-stainless-steel-water-bottle-thermos-adult-lar.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'narutos-new-anime-500ml-stainless-steel-water-bottle-thermos-adult-lar');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'One Piece', 'one-piece', '/images/merchandise/cosplay/one-piece.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'one-piece');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Remera Naruto Uzumaki Anime Algodon Serigrafia Mercadolibre', 'remera-naruto-uzumaki-anime-algodon-serigrafia-mercadolibre', '/images/merchandise/cosplay/remera-naruto-uzumaki-anime-algodon-serigrafia-mercadolibre.jpg', 1
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'remera-naruto-uzumaki-anime-algodon-serigrafia-mercadolibre');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Black Pink', 'black-pink', '/images/merchandise/k-pop/black-pink.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'black-pink');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Black Pink Merchandise', 'black-pink-merchandise', '/images/merchandise/k-pop/black-pink-merchandise.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'black-pink-merchandise');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Blackpink Cartera Hym', 'blackpink-cartera-hym', '/images/merchandise/k-pop/blackpink-cartera-hym.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'blackpink-cartera-hym');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Blackpink Notebook Dairy Shop At Amazon', 'blackpink-notebook-dairy-shop-at-amazon', '/images/merchandise/k-pop/blackpink-notebook-dairy-shop-at-amazon.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'blackpink-notebook-dairy-shop-at-amazon');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Blackpink Parpadeo Coj N', 'blackpink-parpadeo-coj-n', '/images/merchandise/k-pop/blackpink-parpadeo-coj-n.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'blackpink-parpadeo-coj-n');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Bts Cap Only For 430', 'bts-cap-only-for-430', '/images/merchandise/k-pop/bts-cap-only-for-430.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'bts-cap-only-for-430');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Bts Casquette', 'bts-casquette', '/images/merchandise/k-pop/bts-casquette.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'bts-casquette');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Copo Quencher T Rmico Bts Butter Shopee Brasil', 'copo-quencher-t-rmico-bts-butter-shopee-brasil', '/images/merchandise/k-pop/copo-quencher-t-rmico-bts-butter-shopee-brasil.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'copo-quencher-t-rmico-bts-butter-shopee-brasil');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Custom Bts Army Iphone 17 Pro Max Black Slim Case Btsarmy Bts', 'custom-bts-army-iphone-17-pro-max-black-slim-case-btsarmy-bts', '/images/merchandise/k-pop/custom-bts-army-iphone-17-pro-max-black-slim-case-btsarmy-bts.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'custom-bts-army-iphone-17-pro-max-black-slim-case-btsarmy-bts');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Jennie T Shirt', 'jennie-t-shirt', '/images/merchandise/k-pop/jennie-t-shirt.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'jennie-t-shirt');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 01', 'k-pop-item-01', '/images/merchandise/k-pop/k-pop-item-01.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-01');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 02', 'k-pop-item-02', '/images/merchandise/k-pop/k-pop-item-02.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-02');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 03', 'k-pop-item-03', '/images/merchandise/k-pop/k-pop-item-03.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-03');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 04', 'k-pop-item-04', '/images/merchandise/k-pop/k-pop-item-04.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-04');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 05', 'k-pop-item-05', '/images/merchandise/k-pop/k-pop-item-05.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-05');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 06', 'k-pop-item-06', '/images/merchandise/k-pop/k-pop-item-06.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-06');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'K Pop Item 07', 'k-pop-item-07', '/images/merchandise/k-pop/k-pop-item-07.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'k-pop-item-07');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'My Bts Cup', 'my-bts-cup', '/images/merchandise/k-pop/my-bts-cup.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'my-bts-cup');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Stray Kids Maniac Backpack Skzoo K Pop Merch', 'stray-kids-maniac-backpack-skzoo-k-pop-merch', '/images/merchandise/k-pop/stray-kids-maniac-backpack-skzoo-k-pop-merch.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'stray-kids-maniac-backpack-skzoo-k-pop-merch');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Stray Kids Pillow', 'stray-kids-pillow', '/images/merchandise/k-pop/stray-kids-pillow.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'stray-kids-pillow');
INSERT INTO merchandise_items (category_id, name, slug, image_path, is_upcoming)
SELECT c.category_id, 'Stray Kids Skz It Tape Do It Evil Skzoo Speaker Ver Express Ship Rando', 'stray-kids-skz-it-tape-do-it-evil-skzoo-speaker-ver-express-ship-rando', '/images/merchandise/k-pop/stray-kids-skz-it-tape-do-it-evil-skzoo-speaker-ver-express-ship-rando.jpg', 1
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM merchandise_items t WHERE t.slug = 'stray-kids-skz-it-tape-do-it-evil-skzoo-speaker-ver-express-ship-rando');

-- ---------- character_profiles ----------
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Anime Cosplay Photoshoot Ideas Creative Anime Cosplay Poses', 'anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses', '/images/characters/cosplay/anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 05', 'cosplay-item-05', '/images/characters/cosplay/cosplay-item-05.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'cosplay-item-05');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 06', 'cosplay-item-06', '/images/characters/cosplay/cosplay-item-06.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'cosplay-item-06');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 07', 'cosplay-item-07', '/images/characters/cosplay/cosplay-item-07.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'cosplay-item-07');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 08', 'cosplay-item-08', '/images/characters/cosplay/cosplay-item-08.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'cosplay-item-08');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 09', 'cosplay-item-09', '/images/characters/cosplay/cosplay-item-09.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'cosplay-item-09');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Create A Naruto Fashion Designer Outfit', 'create-a-naruto-fashion-designer-outfit', '/images/characters/cosplay/create-a-naruto-fashion-designer-outfit.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'create-a-naruto-fashion-designer-outfit');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Hinata', 'hinata', '/images/characters/cosplay/hinata.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'hinata');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Hinata Y Naruto', 'hinata-y-naruto', '/images/characters/cosplay/hinata-y-naruto.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'hinata-y-naruto');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Kushina', 'kushina', '/images/characters/cosplay/kushina.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'kushina');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Mikey Takes The Lead Tokyo Revengers Drop 2 Fashion Editorial Tokyo Re', 'mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re', '/images/characters/cosplay/mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Roronoa Zoro', 'roronoa-zoro', '/images/characters/cosplay/roronoa-zoro.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'roronoa-zoro');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Union Arena Tcg Bleach Thousand Year War Starter Deck', 'union-arena-tcg-bleach-thousand-year-war-starter-deck', '/images/characters/cosplay/union-arena-tcg-bleach-thousand-year-war-starter-deck.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'union-arena-tcg-bleach-thousand-year-war-starter-deck');
INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Women S Halloween Costume Ideas', 'women-s-halloween-costume-ideas', '/images/characters/cosplay/women-s-halloween-costume-ideas.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles t WHERE t.slug = 'women-s-halloween-costume-ideas');

COMMIT;
