-- Character profiles from the supplied artwork.
-- Generated by scripts/importSuppliedArt.mjs --apply --seed. Do not hand-edit.
-- Safe to re-run: every row is INSERT.. WHERE NOT EXISTS on slug.

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Anime Cosplay Photoshoot Ideas Creative Anime Cosplay Poses', 'anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses', '/images/characters/cosplay/anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'anime-cosplay-photoshoot-ideas-creative-anime-cosplay-poses');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Create A Naruto Fashion Designer Outfit', 'create-a-naruto-fashion-designer-outfit', '/images/characters/cosplay/create-a-naruto-fashion-designer-outfit.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'create-a-naruto-fashion-designer-outfit');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 05', 'cosplay-item-05', '/images/characters/cosplay/cosplay-item-05.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-05');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 06', 'cosplay-item-06', '/images/characters/cosplay/cosplay-item-06.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-06');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 07', 'cosplay-item-07', '/images/characters/cosplay/cosplay-item-07.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-07');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 08', 'cosplay-item-08', '/images/characters/cosplay/cosplay-item-08.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-08');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 09', 'cosplay-item-09', '/images/characters/cosplay/cosplay-item-09.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-09');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Hinata', 'hinata', '/images/characters/cosplay/hinata.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'hinata');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Hinata Y Naruto', 'hinata-y-naruto', '/images/characters/cosplay/hinata-y-naruto.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'hinata-y-naruto');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Kushina', 'kushina', '/images/characters/cosplay/kushina.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'kushina');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Mikey Takes The Lead Tokyo Revengers Drop 2', 'mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re', '/images/characters/cosplay/mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'mikey-takes-the-lead-tokyo-revengers-drop-2-fashion-editorial-tokyo-re');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Roronoa Zoro', 'roronoa-zoro', '/images/characters/cosplay/roronoa-zoro.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'roronoa-zoro');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Union Arena TCG Bleach Thousand Year War Starter', 'union-arena-tcg-bleach-thousand-year-war-starter-deck', '/images/characters/cosplay/union-arena-tcg-bleach-thousand-year-war-starter-deck.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'union-arena-tcg-bleach-thousand-year-war-starter-deck');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Women S Halloween Costume Ideas', 'women-s-halloween-costume-ideas', '/images/characters/cosplay/women-s-halloween-costume-ideas.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'women-s-halloween-costume-ideas');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Sukuna Jjk Walpaper', 'sukuna-jjk-walpaper', '/images/characters/anime/sukuna-jjk-walpaper.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'sukuna-jjk-walpaper');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Anime Item 05', 'anime-item-05', '/images/characters/anime/anime-item-05.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'anime-item-05');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Anime Item 06', 'anime-item-06', '/images/characters/anime/anime-item-06.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'anime-item-06');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Anime Item 07', 'anime-item-07', '/images/characters/anime/anime-item-07.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'anime-item-07');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Kurapika Hxh', 'kurapika-hxh', '/images/characters/anime/kurapika-hxh.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'kurapika-hxh');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Monkey D Luffy', 'monkey-d-luffy', '/images/characters/anime/monkey-d-luffy.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'monkey-d-luffy');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Muzan Kibutsuji', 'muzan-kibutsuji', '/images/characters/anime/muzan-kibutsuji.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'muzan-kibutsuji');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Naruto Wallpaper Download', 'naruto-wallpaper-download', '/images/characters/anime/naruto-wallpaper-download.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'naruto-wallpaper-download');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Embark On An Epic Journey With Saitama From', 'embark-on-an-epic-journey-with-saitama-from-one-punch-man-experience-h', '/images/characters/anime/embark-on-an-epic-journey-with-saitama-from-one-punch-man-experience-h.jpg'
FROM categories c
WHERE c.slug = 'anime'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'embark-on-an-epic-journey-with-saitama-from-one-punch-man-experience-h');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Classic Deadpool', 'classic-deadpool', '/images/characters/comics/classic-deadpool.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'classic-deadpool');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Comics Item 01', 'comics-item-01', '/images/characters/comics/comics-item-01.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'comics-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Comics Item 02', 'comics-item-02', '/images/characters/comics/comics-item-02.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'comics-item-02');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Comics Item 03', 'comics-item-03', '/images/characters/comics/comics-item-03.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'comics-item-03');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Comics Item 04', 'comics-item-04', '/images/characters/comics/comics-item-04.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'comics-item-04');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Harley Quinn', 'harley-quinn', '/images/characters/comics/harley-quinn.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'harley-quinn');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Iron Man 4k Wallpaper Tech Power', 'iron-man-4k-wallpaper-tech-power', '/images/characters/comics/iron-man-4k-wallpaper-tech-power.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'iron-man-4k-wallpaper-tech-power');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'The Wolverine', 'the-wolverine', '/images/characters/comics/the-wolverine.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'the-wolverine');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Wonder Woman', 'wonder-woman', '/images/characters/comics/wonder-woman.jpg'
FROM categories c
WHERE c.slug = 'comics'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'wonder-woman');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 10', 'cosplay-item-10', '/images/characters/cosplay/cosplay-item-10.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-10');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Cosplay Item 11', 'cosplay-item-11', '/images/characters/cosplay/cosplay-item-11.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'cosplay-item-11');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Gojo Wallpaper', 'gojo-wallpaper', '/images/characters/cosplay/gojo-wallpaper.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'gojo-wallpaper');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Tomb Raider Lara Croft', 'tomb-raider-lara-croft', '/images/characters/cosplay/tomb-raider-lara-croft.jpg'
FROM categories c
WHERE c.slug = 'cosplay'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'tomb-raider-lara-croft');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Arthur Morgan Icon 4k', 'arthur-morgan-icon-4k', '/images/characters/gaming/arthur-morgan-icon-4k.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'arthur-morgan-icon-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Chun Li Capcom Streetfighters', 'chun-li-capcom-streetfighters', '/images/characters/gaming/chun-li-capcom-streetfighters.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'chun-li-capcom-streetfighters');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Gaming Item 01', 'gaming-item-01', '/images/characters/gaming/gaming-item-01.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'gaming-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Gaming Item 02', 'gaming-item-02', '/images/characters/gaming/gaming-item-02.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'gaming-item-02');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Gaming Item 03', 'gaming-item-03', '/images/characters/gaming/gaming-item-03.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'gaming-item-03');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Geralt Of Rivia', 'geralt-of-rivia', '/images/characters/gaming/geralt-of-rivia.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'geralt-of-rivia');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'God Of War Kratos Ultra Hd 4k Wallpaper', 'god-of-war-kratos-ultra-hd-4k-wallpaper', '/images/characters/gaming/god-of-war-kratos-ultra-hd-4k-wallpaper.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'god-of-war-kratos-ultra-hd-4k-wallpaper');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Link', 'link', '/images/characters/gaming/link.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'link');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Super Mario Caricature', 'super-mario-caricature', '/images/characters/gaming/super-mario-caricature.jpg'
FROM categories c
WHERE c.slug = 'gaming'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'super-mario-caricature');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Blackpink Item 01', 'blackpink-item-01', '/images/characters/k-pop/blackpink-item-01.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'blackpink-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Blackpink Jisoo', 'blackpink-jisoo', '/images/characters/k-pop/blackpink-jisoo.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'blackpink-jisoo');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Blackpink Lisa Hd Wallpaper 4k', 'blackpink-lisa-hd-wallpaper-4k', '/images/characters/k-pop/blackpink-lisa-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'blackpink-lisa-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Blackpink Rose Blackpink', 'blackpink-rose-blackpink', '/images/characters/k-pop/blackpink-rose-blackpink.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'blackpink-rose-blackpink');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Item 01', 'bts-item-01', '/images/characters/k-pop/bts-item-01.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Item 02', 'bts-item-02', '/images/characters/k-pop/bts-item-02.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-item-02');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Jeon Jungkook', 'bts-jeon-jungkook', '/images/characters/k-pop/bts-jeon-jungkook.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-jeon-jungkook');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Jhope From BTS Wallpaper 4k', 'bts-jhope-from-bts-wallpaper-4k', '/images/characters/k-pop/bts-jhope-from-bts-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-jhope-from-bts-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Jimin Hd Wallpaper', 'bts-jimin-hd-wallpaper', '/images/characters/k-pop/bts-jimin-hd-wallpaper.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-jimin-hd-wallpaper');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Jin BTS Aesthetic Photo Kim Seokjin Kpop', 'bts-jin-bts-aesthetic-photo-kim-seokjin-kpop-edit', '/images/characters/k-pop/bts-jin-bts-aesthetic-photo-kim-seokjin-kpop-edit.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-jin-bts-aesthetic-photo-kim-seokjin-kpop-edit');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'BTS Suga', 'bts-suga', '/images/characters/k-pop/bts-suga.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'bts-suga');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Bang Chan Hd Wallpaper', 'straykids-bang-chan-hd-wallpaper', '/images/characters/k-pop/straykids-bang-chan-hd-wallpaper.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-bang-chan-hd-wallpaper');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Changbin Hd Wallpaper 4k', 'straykids-changbin-hd-wallpaper-4k', '/images/characters/k-pop/straykids-changbin-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-changbin-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Item 01', 'straykids-item-01', '/images/characters/k-pop/straykids-item-01.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Han Jisung Ultra Hd Wallpaper 4k', 'straykids-han-jisung-ultra-hd-wallpaper-4k', '/images/characters/k-pop/straykids-han-jisung-ultra-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-han-jisung-ultra-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Hyunjin Hd Wallpaper 4k', 'straykids-hyunjin-hd-wallpaper-4k', '/images/characters/k-pop/straykids-hyunjin-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-hyunjin-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids I N Ultra Hd Wallpaper 4k', 'straykids-i-n-ultra-hd-wallpaper-4k', '/images/characters/k-pop/straykids-i-n-ultra-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-i-n-ultra-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Lee Felix', 'straykids-lee-felix', '/images/characters/k-pop/straykids-lee-felix.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-lee-felix');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Straykids Seungmin Ultra Hd Wallpaper 4k', 'straykids-seungmin-ultra-hd-wallpaper-4k', '/images/characters/k-pop/straykids-seungmin-ultra-hd-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'straykids-seungmin-ultra-hd-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Chaeyeon Twice', 'twice-chaeyeon-twice', '/images/characters/k-pop/twice-chaeyeon-twice.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-chaeyeon-twice');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice 240807 Tzuyu X Vis E', 'twice-240807-tzuyu-x-vis-e', '/images/characters/k-pop/twice-240807-tzuyu-x-vis-e.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-240807-tzuyu-x-vis-e');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Item 01', 'twice-item-01', '/images/characters/k-pop/twice-item-01.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Item 02', 'twice-item-02', '/images/characters/k-pop/twice-item-02.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-item-02');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Item 03', 'twice-item-03', '/images/characters/k-pop/twice-item-03.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-item-03');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Jeongyeon Instagram And Bbl Update Full Screen', 'twice-jeongyeon-instagram-and-bbl-update-full-screen-wallpapers', '/images/characters/k-pop/twice-jeongyeon-instagram-and-bbl-update-full-screen-wallpapers.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-jeongyeon-instagram-and-bbl-update-full-screen-wallpapers');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Jihyo Ia', 'twice-jihyo-ia', '/images/characters/k-pop/twice-jihyo-ia.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-jihyo-ia');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Momo', 'twice-momo', '/images/characters/k-pop/twice-momo.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-momo');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Twice Scan This Is For World Tour In', 'twice-scan-this-is-for-world-tour-in-incheon-photobook-dahyun', '/images/characters/k-pop/twice-scan-this-is-for-world-tour-in-incheon-photobook-dahyun.jpg'
FROM categories c
WHERE c.slug = 'k-pop'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'twice-scan-this-is-for-world-tour-in-incheon-photobook-dahyun');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Manga Item 01', 'manga-item-01', '/images/characters/manga/manga-item-01.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'manga-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Guts En Combate', 'guts-en-combate', '/images/characters/manga/guts-en-combate.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'guts-en-combate');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Makima After Dark Chainsaw Man', 'makima-after-dark-chainsaw-man', '/images/characters/manga/makima-after-dark-chainsaw-man.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'makima-after-dark-chainsaw-man');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Megumi Fushiguro', 'megumi-fushiguro', '/images/characters/manga/megumi-fushiguro.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'megumi-fushiguro');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Miyamoto Musashi Anime Style Legendary Samurai In Demon', 'miyamoto-musashi-anime-style-legendary-samurai-in-demon-slayer-aesthet', '/images/characters/manga/miyamoto-musashi-anime-style-legendary-samurai-in-demon-slayer-aesthet.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'miyamoto-musashi-anime-style-legendary-samurai-in-demon-slayer-aesthet');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Silver Sovereign', 'silver-sovereign', '/images/characters/manga/silver-sovereign.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'silver-sovereign');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Thorfinn Wallpaper 4k', 'thorfinn-wallpaper-4k', '/images/characters/manga/thorfinn-wallpaper-4k.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'thorfinn-wallpaper-4k');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Yuji Itadori Jujutsu Kaisen Wallpaper Dark Anime Aesthetic', 'yuji-itadori-jujutsu-kaisen-wallpaper-dark-anime-aesthetic', '/images/characters/manga/yuji-itadori-jujutsu-kaisen-wallpaper-dark-anime-aesthetic.jpg'
FROM categories c
WHERE c.slug = 'manga'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'yuji-itadori-jujutsu-kaisen-wallpaper-dark-anime-aesthetic');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, '4 Reasons You Can Believe Jon Snow Will', '4-reasons-you-can-believe-jon-snow-will-rise-again-on-game-of-thrones', '/images/characters/tv-shows/4-reasons-you-can-believe-jon-snow-will-rise-again-on-game-of-thrones.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = '4-reasons-you-can-believe-jon-snow-will-rise-again-on-game-of-thrones');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Discover The Unique Jewellery Worn On Game Of', 'discover-the-unique-jewellery-worn-on-game-of-thrones', '/images/characters/tv-shows/discover-the-unique-jewellery-worn-on-game-of-thrones.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'discover-the-unique-jewellery-worn-on-game-of-thrones');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'TV Shows Item 01', 'tv-shows-item-01', '/images/characters/tv-shows/tv-shows-item-01.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'tv-shows-item-01');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Garret Graham', 'garret-graham', '/images/characters/tv-shows/garret-graham.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'garret-graham');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Loki', 'loki', '/images/characters/tv-shows/loki.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'loki');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Moody Portrait Of A Girl With Braided Hair', 'moody-portrait-of-a-girl-with-braided-hair-and-a-gothic-minimalist-sty', '/images/characters/tv-shows/moody-portrait-of-a-girl-with-braided-hair-and-a-gothic-minimalist-sty.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'moody-portrait-of-a-girl-with-braided-hair-and-a-gothic-minimalist-sty');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'The Walking Dead 5 Temporada Fotos Promocionais Dos', 'the-walking-dead-5-temporada-fotos-promocionais-dos-personagens-geekda', '/images/characters/tv-shows/the-walking-dead-5-temporada-fotos-promocionais-dos-personagens-geekda.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'the-walking-dead-5-temporada-fotos-promocionais-dos-personagens-geekda');

INSERT INTO character_profiles (category_id, name, slug, image_path)
SELECT c.category_id, 'Thomas Shelby', 'thomas-shelby', '/images/characters/tv-shows/thomas-shelby.jpg'
FROM categories c
WHERE c.slug = 'tv-shows'
  AND NOT EXISTS (SELECT 1 FROM character_profiles p WHERE p.slug = 'thomas-shelby');
