// applySynopses.mjs, writes reviewed synopses into src/data/catalog.json and
// emits the SQL UPDATE for contents.synopsis / short_synopsis.
//
// Input: data/synopses.json, keyed by fandom then slug, each holding a synopsis and a shortSynopsis
// Output: src/data/catalog.json updated in place
//         database/07_synopsis_seed.sql
//
// A title absent from the input is left untouched, so an unreviewed title stays
// NULL rather than picking up a placeholder.
//
// THE UPDATE IS SCOPED TO A CATEGORY, and it has to be. `contents.slug` is
// unique per category, not globally: "akira" is a film, a manga and an anime,
// "django" is a film and a comic. Matching on slug alone makes 93 statements in
// the generated file overwrite a sibling fandom's row, with the last one to run
// winning. The three works are different and each has its own reviewed text, so
// the join is what makes the file correct rather than merely faster.
//
//   UPDATE contents c JOIN categories g ON g.category_id = c.category_id
//   SET c.synopsis =..., c.short_synopsis =. WHERE c.slug =. AND g.slug =...;
//
// Usage: node scripts/applySynopses.mjs

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { FANDOMS, FANDOM_KEYS } from "./lib/catalogParse.mjs";

const CATALOG = "src/data/catalog.json";
const INPUT = "data/synopses.json";
const OUT_SQL = "database/07_synopsis_seed.sql";

const SHORT_MAX = 300;
const CONTENT_TYPES = new Set(Object.values(FANDOMS).map((f) => f.contentType));

function sql(value) {
  if (value === null || value === undefined || value === "") return "NULL";
  return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}

const catalog = JSON.parse(readFileSync(CATALOG, "utf8"));
const raw = JSON.parse(readFileSync(INPUT, "utf8"));

let applied = 0;
let unmatched = 0;
let tooLong = 0;
const unknownKeys = [];

for (const row of catalog) {
  const key = `${row.fandom}|${row.slug}`;
  const entry = raw[key];
  if (!entry) continue;

  if (!entry.synopsis || !String(entry.synopsis).trim()) continue;

  const short = String(entry.shortSynopsis ?? "").trim();
  if (short.length > SHORT_MAX) {
    console.warn(`shortSynopsis over ${SHORT_MAX} chars, NULLing: ${key}`);
    tooLong++;
    row.synopsis = String(entry.synopsis).trim();
    row.shortSynopsis = null;
  } else {
    row.synopsis = String(entry.synopsis).trim();
    row.shortSynopsis = short || null;
  }
  applied++;
}

const catalogKeys = new Set(catalog.map((r) => `${r.fandom}|${r.slug}`));
for (const key of Object.keys(raw)) {
  if (!catalogKeys.has(key)) unknownKeys.push(key);
}

writeFileSync(CATALOG, JSON.stringify(catalog, null, 1));

const lines = [
  "-- Generated by scripts/applySynopses.mjs. Do not edit by hand.",
  "-- synopsis + short_synopsis for reviewed titles only; unlisted rows stay NULL.",
  "",
  "START TRANSACTION;",
  "",
];

const unmapped = new Set();

for (const row of catalog) {
  if (!row.synopsis) continue;

  // catalog.json's categorySlug is a frontend key, not the database slug. Three
  // of the six differ, and an UPDATE scoped by the wrong one matches no row and
  // fails silently — which is how all 448 TV Shows synopses went missing once.
  const dbSlug = FANDOM_KEYS[row.fandom];
  if (!dbSlug) {
    unmapped.add(row.fandom);
    continue;
  }

  lines.push(
    `UPDATE contents c JOIN categories g ON g.category_id = c.category_id SET c.synopsis = ${sql(row.synopsis)}, c.short_synopsis = ${sql(row.shortSynopsis)} WHERE c.slug = ${sql(row.slug)} AND g.slug = ${sql(dbSlug)};`,
  );
}

// ---- merged duplicates ----------------------------------------------------
//
// The 04_* seeds come from the raw source lists. catalog.json is the same data
// after dedupeCatalog.mjs merged near-duplicate titles: "Death Note" and "Death
// Note Thriller" are one work, so the catalogue has one row and the seed has two.
// A visitor can still reach the second row, and an UPDATE scoped to one slug
// leaves it blank — the page renders "No description yet" for a title that
// plainly has one.
//
// So the dropped slug is given its merged sibling's text. It is the same work
// and the same description, which is the correct answer for both rows; the
// catalogue and the database simply differ on how many rows to keep it in.
let merged = 0;
const mergedNote = [];

// Scoped per fandom: a seed slug may only inherit from a catalogue row in the
// same fandom. Comparing across fandoms would let a film donate its synopsis to
// a television show that happens to share a prefix.
const slugsWithSynopsisByFandom = new Map();
for (const r of catalog) {
  if (!r.synopsis) continue;
  if (!slugsWithSynopsisByFandom.has(r.fandom)) slugsWithSynopsisByFandom.set(r.fandom, new Set());
  slugsWithSynopsisByFandom.get(r.fandom).add(r.slug);
}

for (const file of readdirSync("database").filter((f) => f.startsWith("04_"))) {
  const text = readFileSync(`database/${file}`, "utf8");

  const cat = text.match(/INSERT INTO categories \(category_id, slug, name, description\) VALUES \(\d+, '([a-z-]+)'/);
  if (!cat) continue;
  const dbSlug = cat[1];

  const fandom = Object.keys(FANDOMS).find((k) => FANDOMS[k].categorySlug === dbSlug);
  if (!fandom) continue;

  const donors = slugsWithSynopsisByFandom.get(fandom) ?? new Set();

  const seedSlugs = [...text.matchAll(/^\s*\(\d+, \d+, '((?:[^']|'')*)', '((?:[^']|'')*)', '([a-z_]+)'/gm)]
    .filter((m) => CONTENT_TYPES.has(m[3]))
    .map((m) => m[2]);

  for (const slug of seedSlugs) {
    if (catalogKeys.has(`${fandom}|${slug}`)) continue;

    // A merged row's slug is its kept sibling's plus a trailing genre name, so
    // the longest catalogue slug that prefixes it is the row to inherit from.
    const donor = [...donors]
      .filter((s) => slug.startsWith(s) && slug !== s)
      .sort((a, b) => b.length - a.length)[0];
    if (!donor) continue;

    const row = catalog.find((r) => r.fandom === fandom && r.slug === donor);
    if (!row?.synopsis) continue;

    lines.push(
      `UPDATE contents c JOIN categories g ON g.category_id = c.category_id SET c.synopsis = ${sql(row.synopsis)}, c.short_synopsis = ${sql(row.shortSynopsis)} WHERE c.slug = ${sql(slug)} AND g.slug = ${sql(dbSlug)};`,
    );
    merged++;
    if (mergedNote.length < 5) mergedNote.push(`${slug} -> ${donor}`);
  }
}

lines.push("", "COMMIT;", "");
writeFileSync(OUT_SQL, lines.join("\n"));

console.log(`applied:      ${applied}`);
console.log(`skipped long: ${tooLong}`);
console.log(`merged duplicates filled: ${merged}`);
if (mergedNote.length) for (const m of mergedNote) console.log(`  ${m}`);
console.log(`unmatched keys in input: ${unknownKeys.length}`);
for (const k of unknownKeys.slice(0, 20)) console.log(`  no such title: ${k}`);
if (unmapped.size) {
  console.log(`FANDOMS WITH NO DATABASE CATEGORY MAPPING: ${[...unmapped].join(", ")}`);
  process.exitCode = 1;
}
console.log(`wrote ${CATALOG} and ${OUT_SQL}`);
