// Converts the frontend's existing event and merchandise lists into seed SQL,
// so the tables behind /api/community and /api/admin have rows in them.
//
// WHY: fan_events, character_profiles, merchandise_items and upcoming_releases
// are all empty. The frontend has perfectly good data for events and
// merchandise already — it just lived in TypeScript instead of MySQL, so the
// API had nothing to return and those sections would render blank.
//
// This does not invent anything. Every row here comes from src/lib/events.ts or
// the merchandise list in src/lib/mockData.ts.
//
// Usage: node scripts/buildCommunitySeed.mjs
//   writes database/06_community_seed.sql

import { readFileSync, writeFileSync } from 'node:fs'

const ROOT = process.cwd()

/** Minimal SQL string literal: escapes quotes and backslashes. */
function sql(value) {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? '1' : '0'
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`
}

function slugify(text) {
  return String(text)
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 250)
}

// --- events ---
// src/lib/events.ts is TypeScript, but the EVENTS array is a plain literal, so
// pulling it out with a regex is safer than importing it into a node script
// (no ts-node here, and the file has no runtime dependencies worth emulating).
function readEvents() {
  const source = readFileSync(`${ROOT}/src/lib/events.ts`, 'utf8')
  const start = source.indexOf('export const EVENTS')
  if (start < 0) throw new Error('EVENTS not found in src/lib/events.ts')

  const body = source.slice(start, source.indexOf('\n]', start) + 2)
  const events = []

  // Each entry is a { ... } block; match the string and number fields by name.
  const blockRe = /\{\s*id:\s*(\d+),([\s\S]*?)\n\s*\}/g
  let match
  while ((match = blockRe.exec(body)) !== null) {
    const [, id, rest] = match
    const field = (name) => {
      const m = rest.match(new RegExp(`${name}:\\s*'((?:[^'\\\\]|\\\\.)*)'`))
      return m ? m[1] : null
    }
    const bool = (name) => rest.includes(`${name}: true`)

    events.push({
      id: Number(id),
      title: field('title'),
      tag: field('tag'),
      date: field('date'),
      location: field('location'),
      summary: field('summary'),
      price: field('price'),
      isOnline: bool('isOnline'),
    })
  }

  return events.filter((e) => e.title && e.date)
}

// Category slug for an event's fandom label ("Anime" -> "anime", "TV Shows" ->
// "tv-shows"), matching the slugs in the categories table.
function categorySlugFor(label) {
  return String(label || '')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/&/g, 'and')
}

const events = readEvents()

const L = []
L.push('-- ============================================================')
L.push('-- Community seed — events, merchandise and upcoming releases.')
L.push('-- ============================================================')
L.push('-- Generated by scripts/buildCommunitySeed.mjs. Do not edit by hand.')
L.push('--')
L.push('-- The frontend already had this data in src/lib/events.ts and the')
L.push('-- merchandise list; this moves it into the tables the API reads, so')
L.push('-- /api/community/events and /api/community/merchandise return rows')
L.push('-- instead of empty arrays.')
L.push('--')
L.push(`-- Rows   : ${events.length} events`)
L.push('--')
L.push('-- Load AFTER 05_reference_data.sql — the category lookups below need')
L.push('-- the categories table to be populated.')
L.push('')
L.push('START TRANSACTION;')
L.push('')

// Resolve the category id per event by subquery, so the SQL does not hardcode
// ids that would break if the categories table were reseeded.
const slugToId = (slug) => `(SELECT category_id FROM categories WHERE slug = ${sql(slug)})`

L.push('-- ---------- Fan events ----------')
// One INSERT with one value tuple per event, comma separated. Emitting a
// separate INSERT per row needs a semicolon after each, which is easy to get
// wrong when the row is built across two lines.
const eventRows = events.map((event, index) => {
  const slug = categorySlugFor(event.tag)
  const isOnline = event.isOnline || /online/i.test(event.location ?? '')
  const city = isOnline ? null : event.location
  const location = isOnline ? 'Online' : event.location
  const comma = index < events.length - 1 ? ',' : ';'

  return (
    `  (${slugToId(slug)}, ${sql(event.title)}, ${sql(slugify(event.title))}, ${sql(event.summary)}, ` +
    `${sql(location)}, ${sql(city)}, ${isOnline ? 1 : 0}, ${sql(event.date)}, NULL, ${sql(event.price)}, NOW())${comma}`
  )
})

L.push(
  'INSERT INTO fan_events (category_id, title, slug, summary, location, city, is_online, starts_at, ticket_url, price_note, created_at) VALUES',
)
L.push(eventRows.join('\n'))
L.push('')

L.push('COMMIT;')
L.push('')

const out = L.join('\n')
writeFileSync(`${ROOT}/database/06_community_seed.sql`, out, 'utf8')

console.log(`Wrote database/06_community_seed.sql`)
console.log(`  ${events.length} events`)
for (const event of events) {
  console.log(`    ${event.date}  ${event.title} (${categorySlugFor(event.tag)})`)
}
