// Reconciles contents.poster_path with the image files that are actually on disk.
//
// WHY THIS EXISTS
//   Two different naming conventions ended up side by side. The enrichment run
//   wrote TMDB's own hash into poster_path (/images/movies/zhG3vKWyDRaZ....jpg)
//   while the downloaded files were saved under the catalogue slug
//   (12-angry-men.jpg). Every one of those 513 paths is a dead link.
//
//   This rewrites each row to the slug-based path when that file exists, and
//   clears poster_path to NULL when it does not. A NULL is honest: the
//   frontend falls back to the generated glyph rather than showing a broken
//   image.
//
//   Run with --apply to write the changes, or with no flag to just report.
//
// Usage:
//   node scripts/fixPosterPaths.mjs            # report only
//   node scripts/fixPosterPaths.mjs --apply    # write to the database

import { readdirSync, existsSync, writeFileSync, readFileSync } from 'node:fs'
import { execFileSync, spawnSync } from 'node:child_process'

const APPLY = process.argv.includes('--apply')

const MYSQL = 'C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin\\mysql.exe'
const PASSWORD = process.env.FANHUB_DB_PASSWORD
const ROOT = process.cwd()

if (!PASSWORD) {
  console.error('Set FANHUB_DB_PASSWORD to the MySQL root password first.')
  process.exit(1)
}

// The images on disk are grouped by folder name, which is not always the
// category slug: gaming -> games, k-pop -> kpop, tv-shows -> tvshows.
const DIR_BY_CATEGORY = {
  movies: 'movies',
  anime: 'anime',
  gaming: 'games',
  comics: 'comics',
  'k-pop': 'kpop',
  'tv-shows': 'tvshows',
  manga: 'manga',
  cosplay: 'cosplay',
}

function query(sql) {
  const out = execFileSync(MYSQL, ['-u', 'root', '-N', '--default-character-set=utf8mb4', '-e', sql], {
    env: { ...process.env, MYSQL_PWD: PASSWORD },
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  return out.split('\n').filter(Boolean)
}

const rows = query(`
  SELECT c.content_id, c.slug, cat.slug, IFNULL(c.poster_path, '')
  FROM fanhubplus.contents c
  JOIN fanhubplus.categories cat ON cat.category_id = c.category_id
  ORDER BY c.content_id;
`).map((line) => {
  const [id, slug, category, current] = line.split('\t')
  return { id: Number(id), slug, category, current }
})

const perCategory = new Map()
let linked = 0
let cleared = 0
const sql = []
const missingByCategory = new Map()

for (const row of rows) {
  const dir = DIR_BY_CATEGORY[row.category]
  if (!dir) continue

  const bucket = perCategory.get(row.category) ?? { total: 0, linked: 0, cleared: 0, hadPath: 0 }
  bucket.total++

  const file = `${ROOT}/public/images/${dir}/${row.slug}.jpg`
  if (existsSync(file)) {
    const next = `/images/${dir}/${row.slug}.jpg`
    if (row.current !== next) {
      sql.push(
        `UPDATE contents SET poster_path = '${next}' WHERE content_id = ${row.id};`,
      )
    }
    linked++
    bucket.linked++
  } else {
    if (row.current !== '') {
      sql.push(`UPDATE contents SET poster_path = NULL WHERE content_id = ${row.id};`)
    }
    cleared++
    bucket.cleared++
    if (row.current !== '') bucket.hadPath++
    missingByCategory.set(row.category, (missingByCategory.get(row.category) ?? 0) + 1)
  }

  perCategory.set(row.category, bucket)
}

console.log('Category coverage\n' + '-'.repeat(64))
for (const [category, b] of perCategory) {
  const pct = b.total ? Math.round((b.linked / b.total) * 100) : 0
  console.log(
    `  ${category.padEnd(10)} ${String(b.linked).padStart(4)}/${String(b.total).padEnd(5)} linked` +
      `  (${String(pct).padStart(3)}%)   no file: ${b.cleared}`,
  )
}

console.log('\nImages on disk that no catalogue row can use:')
for (const dir of Object.values(DIR_BY_CATEGORY)) {
  const p = `${ROOT}/public/images/${dir}`
  if (!existsSync(p)) continue
  const files = readdirSync(p).filter((f) => f.toLowerCase().endsWith('.jpg'))
  const usedSlugs = new Set(
    rows.filter((r) => DIR_BY_CATEGORY[r.category] === dir).map((r) => r.slug),
  )
  const orphans = files.filter((f) => !usedSlugs.has(f.replace(/\.jpg$/i, '')))
  if (orphans.length) {
    console.log(`  ${dir}: ${orphans.length} unused (no matching content row)`)
  }
}

console.log(`\n${sql.length} statements prepared.`)
console.log(`  ${linked} rows point at a real file, ${cleared} cleared to NULL.`)

if (!APPLY) {
  console.log('\nDry run. Re-run with --apply to write these changes.')
  process.exit(0)
}

const outFile = `${ROOT}/scripts/.poster-paths.sql`
writeFileSync(
  outFile,
  `-- Generated by scripts/fixPosterPaths.mjs. Points poster_path at files that\n` +
    `-- actually exist under public/images/, and NULL where none does.\n` +
    `START TRANSACTION;\n${sql.join('\n')}\nCOMMIT;\n`,
  'utf8',
)

// Feed the SQL over stdin rather than shelling out to `type ... | mysql`.
// The cmd.exe pipe fails on paths with spaces, and reading the file here keeps
// the encoding explicit.
const mysql = spawnSync(
  MYSQL,
  ['-u', 'root', '--default-character-set=utf8mb4', 'fanhubplus'],
  {
    env: { ...process.env, MYSQL_PWD: PASSWORD },
    input: readFileSync(outFile, 'utf8'),
    encoding: 'utf8',
  },
)

if (mysql.status !== 0) {
  console.error(mysql.stderr || 'mysql exited non-zero')
  process.exit(1)
}

console.log('\nApplied. Verifying:')
const after = query(
  `SELECT COUNT(*) FROM fanhubplus.contents WHERE poster_path IS NOT NULL AND poster_path <> '';`,
)
console.log(`  rows with a poster_path: ${after[0]}`)
